// Plik: app/constants/hydroLevels.js
// Stałe dane poziomów hydrologicznych dla stacji

/**
 * Dane poziomów hydrologicznych dla poszczególnych stacji.
 * Zawiera informacje o stanach alarmowych i ostrzegawczych.
 * 
 * Struktura:
 * {
 *   stationName: string - nazwa stacji
 *   warningLevel: number - stan ostrzegawczy w cm
 *   alarmLevel: number - stan alarmowy w cm
 * }
 */
export const HYDRO_LEVELS = [

  { stationName: "Warszawa", warningLevel: 600, alarmLevel: 650 },
  { stationName: "Kraków", warningLevel: 500, alarmLevel: 550 },
  { stationName: "Płock", warningLevel: 700, alarmLevel: 800 },
  { stationName: "Tczew", warningLevel: 820, alarmLevel: 850 },
  { stationName: "Włocławek", warningLevel: 650, alarmLevel: 700 },
  { stationName: "Toruń", warningLevel: 550, alarmLevel: 650 },
  { stationName: "Puławy", warningLevel: 400, alarmLevel: 450 },
  { stationName: "Sandomierz", warningLevel: 580, alarmLevel: 630 },
  { stationName: "Wrocław", warningLevel: 520, alarmLevel: 600 },
  { stationName: "Opole", warningLevel: 480, alarmLevel: 550 },
  { stationName: "Brzeg Dolny", warningLevel: 490, alarmLevel: 540 },
  { stationName: "Głogów", warningLevel: 450, alarmLevel: 530 },
  { stationName: "Słubice", warningLevel: 430, alarmLevel: 480 },
  { stationName: "Szczecin", warningLevel: 550, alarmLevel: 600 },
  { stationName: "Gozdowice", warningLevel: 480, alarmLevel: 530 },
  { stationName: "Poznań", warningLevel: 400, alarmLevel: 450 },
  { stationName: "Gorzów Wielkopolski", warningLevel: 380, alarmLevel: 430 },
  { stationName: "Śrem", warningLevel: 350, alarmLevel: 400 },
  { stationName: "Sieradz", warningLevel: 320, alarmLevel: 370 },
  { stationName: "Działoszyn", warningLevel: 290, alarmLevel: 340 },
  { stationName: "Przewoźniki", warningLevel: 220, alarmLevel: 240 },
  { stationName: "Branice",warningLevel: 180,alarmLevel: 240 },
  { stationName: "Dębe",warningLevel: 220,alarmLevel: 250 },
  { stationName: "Iława",warningLevel: 930,alarmLevel: 940 },
  { stationName: "Kłodzko",warningLevel: 160,alarmLevel: 240 },
  { stationName: "Krąplewice",warningLevel: 220,alarmLevel: 280 },
  { stationName: "Kwiatkówek",warningLevel: 200,alarmLevel: 250 },
  { stationName: "Leśna",warningLevel: 70,alarmLevel: 100 },
  { stationName: "Lubachów",warningLevel: 210,alarmLevel: 230 },
  { stationName: "Mirsk",warningLevel: 160,alarmLevel: 200 },
  { stationName: "Pilchowice",warningLevel: 100,alarmLevel: 140 },
  { stationName: "Rogóźno 2",warningLevel: 230,alarmLevel: 260 },
  { stationName: "Rydzyna",warningLevel: 200,alarmLevel: 240 },
  { stationName: "Babino",warningLevel: 540,alarmLevel: 570 },
  { stationName: "Balice",warningLevel: 340,alarmLevel: 380 },
  { stationName: "Barcinek",warningLevel: 80,alarmLevel: 110 },
  { stationName: "Bardo",warningLevel: 180,alarmLevel: 250 },
  { stationName: "Bardy",warningLevel: 360,alarmLevel: 400 },
  { stationName: "Bągart",warningLevel: 790,alarmLevel: 800 },
  { stationName: "Biała Góra",warningLevel: 360,alarmLevel: 470 },
  { stationName: "Białobrzeg Bliższy",warningLevel: 180,alarmLevel: 220 },
  { stationName: "Białobrzegi",warningLevel: 200,alarmLevel: 250 },
  { stationName: "Białobrzezie",warningLevel: 90,alarmLevel: 120 },
  { stationName: "Białogard",warningLevel: 270,alarmLevel: 290 },
  { stationName: "Białogórzyno",warningLevel: 190,alarmLevel: 210 },
  { stationName: "Białowieża-Park",warningLevel: 180,alarmLevel: 200 },
  { stationName: "Bielawy",warningLevel: 310,alarmLevel: 360 },
  { stationName: "Bielinek",warningLevel: 480,alarmLevel: 550 },
  { stationName: "Bieruń Nowy",warningLevel: 220,alarmLevel: 330 },
  { stationName: "Biłgoraj",warningLevel: 180,alarmLevel: 220 },
  { stationName: "Biskupice",warningLevel: 410,alarmLevel: 450 },
  { stationName: "Bledzew",warningLevel: 200,alarmLevel: 220 },
  { stationName: "Bobry",warningLevel: 130,alarmLevel: 150 },
  { stationName: "Bocheniec",warningLevel: 320,alarmLevel: 370 },
  { stationName: "Bogatynia",warningLevel: 100,alarmLevel: 125 },
  { stationName: "Bogdaj",warningLevel: 250,alarmLevel: 300 },
  { stationName: "Bogusław",warningLevel: 250,alarmLevel: 300 },
  { stationName: "Bojanów",warningLevel: 150,alarmLevel: 210 },
  { stationName: "Bornity",warningLevel: 380,alarmLevel: 440 },
  { stationName: "Borów",warningLevel: 160,alarmLevel: 200 },
  { stationName: "Bożepole Szlacheckie",warningLevel: 150,alarmLevel: 180 },
  { stationName: "Branice",warningLevel: 180,alarmLevel: 240 },
  { stationName: "Braniewo",warningLevel: 720,alarmLevel: 780 },
  { stationName: "Brodnica",warningLevel: 230,alarmLevel: 260 },
  { stationName: "Brody Iłżeckie",warningLevel: 200,alarmLevel: 270 },
  { stationName: "Brody Pomorskie",warningLevel: 320,alarmLevel: 350 },
  { stationName: "Brynica",warningLevel: 180,alarmLevel: 220 },
  { stationName: "Brzeg",warningLevel: 460,alarmLevel: 530 },
  { stationName: "Brzeg Dolny",warningLevel: 510,alarmLevel: 630 },
  { stationName: "Bukowna",warningLevel: 120,alarmLevel: 150 },
  { stationName: "Bukówka",warningLevel: 150,alarmLevel: 180 },
  { stationName: "Bystrzyca Kłodzka",warningLevel: 80,alarmLevel: 120 },
  { stationName: "Bystrzyca Kłodzka",warningLevel: 110,alarmLevel: 180 },
  { stationName: "Chałupki",warningLevel: 300,alarmLevel: 420 },
  { stationName: "Charnowo",warningLevel: 290,alarmLevel: 340 },
  { stationName: "Chojnów",warningLevel: 120,alarmLevel: 150 },
  { stationName: "Chraboły",warningLevel: 310,alarmLevel: 350 },
  { stationName: "Chwaliszów",warningLevel: 200,alarmLevel: 250 },
  { stationName: "Cieszyn",warningLevel: 140,alarmLevel: 230 },
  { stationName: "Cięcina",warningLevel: 280,alarmLevel: 360 },
  { stationName: "Cigacice",warningLevel: 350,alarmLevel: 400 },
  { stationName: "Czaniec-Kobiernice",warningLevel: 320,alarmLevel: 450 },
  { stationName: "Czarnków",warningLevel: 250,alarmLevel: 300 },
  { stationName: "Czarnowo",warningLevel: 270,alarmLevel: 320 },
  { stationName: "Czechowice-Bestwina",warningLevel: 190,alarmLevel: 260 },
  { stationName: "Daleszyce",warningLevel: 200,alarmLevel: 260 },
  { stationName: "Darłowo",warningLevel: 570,alarmLevel: 610 },
  { stationName: "Dąbrowa",warningLevel: 370,alarmLevel: 400 },
  { stationName: "Dobra",warningLevel: 140,alarmLevel: 200 },
  { stationName: "Domaradz",warningLevel: 200,alarmLevel: 250 },
  { stationName: "Drawiny",warningLevel: 120,alarmLevel: 170 },
  { stationName: "Dwernik",warningLevel: 200,alarmLevel: 260 },
  { stationName: "Dynów",warningLevel: 300,alarmLevel: 460 },
  { stationName: "Dziarny",warningLevel: 130,alarmLevel: 140 },
  { stationName: "Dzierżoniów",warningLevel: 280,alarmLevel: 300 },
  { stationName: "Dziwnów",warningLevel: 560,alarmLevel: 580 },
  { stationName: "Elbląg",warningLevel: 590,alarmLevel: 610 },
  { stationName: "Elgiszewo",warningLevel: 200,alarmLevel: 230 },
  { stationName: "Ełk",warningLevel: 220,alarmLevel: 235 },
  { stationName: "Gardna Wielka",warningLevel: 570,alarmLevel: 610 },
  { stationName: "Gdańsk - Port Północny",warningLevel: 550,alarmLevel: 570 },
  { stationName: "Gdańsk - Przegalina",warningLevel: 650,alarmLevel: 700 },
  { stationName: "Gdańsk - Sobieszewo",warningLevel: 550,alarmLevel: 570 },
  { stationName: "Gdańsk - Świbno",warningLevel: 600,alarmLevel: 680 },
  { stationName: "Gdańsk - Ujście Wisły",warningLevel: 600,alarmLevel: 680 },
  { stationName: "Gdańska Głowa",warningLevel: 730,alarmLevel: 810 },
  { stationName: "Gdynia",warningLevel: 550,alarmLevel: 570 },
  { stationName: "Głogów",warningLevel: 400,alarmLevel: 450 },
  { stationName: "Głowaczowa",warningLevel: 220,alarmLevel: 300 },
  { stationName: "Gniechowice",warningLevel: 150,alarmLevel: 180 },
  { stationName: "Goczałkowice",warningLevel: 290,alarmLevel: 410 },
  { stationName: "Goleniów",warningLevel: 270,alarmLevel: 320 },
  { stationName: "Gołdap 2",warningLevel: 180,alarmLevel: 210 },
  { stationName: "Gorzów Śląski",warningLevel: 160,alarmLevel: 210 },
  { stationName: "Gorzuchów",warningLevel: 120,alarmLevel: 160 },
  { stationName: "Gościmiec",warningLevel: 290,alarmLevel: 380 },
  { stationName: "Gozdowice",warningLevel: 440,alarmLevel: 500 },
  { stationName: "Gozdów",warningLevel: 290,alarmLevel: 350 },
  { stationName: "Górki Wielkie",warningLevel: 220,alarmLevel: 260 },
  { stationName: "Grabno",warningLevel: 230,alarmLevel: 280 },
  { stationName: "Grabówka",warningLevel: 90,alarmLevel: 140 },
  { stationName: "Grębów",warningLevel: 320,alarmLevel: 400 },
  { stationName: "Grudziądz",warningLevel: 540,alarmLevel: 650 },
  { stationName: "Grybów",warningLevel: 320,alarmLevel: 400 },
  { stationName: "Gryfino",warningLevel: 570,alarmLevel: 600 },
  { stationName: "Gryfów Śląski",warningLevel: 220,alarmLevel: 260 },
  { stationName: "Grzegorzew",warningLevel: 240,alarmLevel: 280 },
  { stationName: "Gubin",warningLevel: 300,alarmLevel: 400 },
  { stationName: "Harasimowicze",warningLevel: 590,alarmLevel: 620 },
  { stationName: "Hel",warningLevel: 550,alarmLevel: 570 },
  { stationName: "Hoczew",warningLevel: 200,alarmLevel: 260 },
  { stationName: "Iłowa",warningLevel: 180,alarmLevel: 200 },
  { stationName: "Istebna",warningLevel: 190,alarmLevel: 210 },
  { stationName: "Izbica",warningLevel: 560,alarmLevel: 600 },
  { stationName: "Jakuszyce",warningLevel: 80,alarmLevel: 120 },
  { stationName: "Januszewice",warningLevel: 360,alarmLevel: 410 },
  { stationName: "Jarnołtów",warningLevel: 230,alarmLevel: 270 },
  { stationName: "Jarnołtówek",warningLevel: 120,alarmLevel: 170 },
  { stationName: "Jarosław",warningLevel: 440,alarmLevel: 620 },
  { stationName: "Jasło",warningLevel: 300,alarmLevel: 420 },
  { stationName: "Jawiszowice",warningLevel: 480,alarmLevel: 630 },
  { stationName: "Jawor",warningLevel: 100,alarmLevel: 150 },
  { stationName: "Jelenia Góra",warningLevel: 160,alarmLevel: 220 },
  { stationName: "Jelenia Góra",warningLevel: 160,alarmLevel: 200 },
  { stationName: "Jugowice",warningLevel: 180,alarmLevel: 230 },
  { stationName: "Jurkiszki",warningLevel: 180,alarmLevel: 210 },
  { stationName: "Kalnica",warningLevel: 370,alarmLevel: 420 },
  { stationName: "Kamesznica",warningLevel: 210,alarmLevel: 260 },
  { stationName: "Kamienna Góra",warningLevel: 120,alarmLevel: 180 },
  { stationName: "Kanclerzowice",warningLevel: 230,alarmLevel: 260 },
  { stationName: "Karłowice",warningLevel: 250,alarmLevel: 300 },
  { stationName: "Karpowicze",warningLevel: 290,alarmLevel: 330 },
  { stationName: "Kęszyce",warningLevel: 350,alarmLevel: 400 },
  { stationName: "Kłudzice",warningLevel: 350,alarmLevel: 380 },
  { stationName: "Kołobrzeg",warningLevel: 570,alarmLevel: 610 },
  { stationName: "Koniówka",warningLevel: 250,alarmLevel: 290 },
  { stationName: "Kopice",warningLevel: 300,alarmLevel: 380 },
  { stationName: "Koprzywnica",warningLevel: 290,alarmLevel: 360 },
  { stationName: "Korzeńsko",warningLevel: 220,alarmLevel: 260 },
  { stationName: "Korzybie",warningLevel: 130,alarmLevel: 160 },
  { stationName: "Kostrzyn Nad Odrą",warningLevel: 360,alarmLevel: 410 },
  { stationName: "Kostrzyn Nad Odrą",warningLevel: 420,alarmLevel: 470 },
  { stationName: "Koszyce Wielkie",warningLevel: 330,alarmLevel: 440 },
  { stationName: "Kościan",warningLevel: 180,alarmLevel: 210 },
  { stationName: "Kowary",warningLevel: 100,alarmLevel: 150 },
  { stationName: "Kozłowa Góra",warningLevel: 90,alarmLevel: 120 },
  { stationName: "Koźle",warningLevel: 400,alarmLevel: 500 },
  { stationName: "Kraków-Bielany",warningLevel: 370,alarmLevel: 520 },
  { stationName: "Krapkowice",warningLevel: 340,alarmLevel: 450 },
  { stationName: "Kraszewice",warningLevel: 240,alarmLevel: 260 },
  { stationName: "Krosno",warningLevel: 360,alarmLevel: 400 },
  { stationName: "Krówniki",warningLevel: 400,alarmLevel: 650 },
  { stationName: "Krubice",warningLevel: 220,alarmLevel: 280 },
  { stationName: "Krzywa Góra",warningLevel: 170,alarmLevel: 240 },
  { stationName: "Krzyż",warningLevel: 360,alarmLevel: 400 },
  { stationName: "Krzyżanowice",warningLevel: 150,alarmLevel: 200 },
  { stationName: "Krzyżanowice",warningLevel: 360,alarmLevel: 500 },
  { stationName: "Kuligi",warningLevel: 150,alarmLevel: 180 },
  { stationName: "Kunów",warningLevel: 200,alarmLevel: 300 },
  { stationName: "Kwidzyn",warningLevel: 300,alarmLevel: 340 },
  { stationName: "Lenartowice",warningLevel: 210,alarmLevel: 260 },
  { stationName: "Lesko",warningLevel: 250,alarmLevel: 330 },
  { stationName: "Leżachów",warningLevel: 460,alarmLevel: 660 },
  { stationName: "Lębork 2",warningLevel: 150,alarmLevel: 200 },
  { stationName: "Lidzbark",warningLevel: 110,alarmLevel: 120 },
  { stationName: "Lubartów",warningLevel: 430,alarmLevel: 480 },
  { stationName: "Łagisza",warningLevel: 200,alarmLevel: 240 },
  { stationName: "Łask",warningLevel: 160,alarmLevel: 180 },
  { stationName: "Łażany",warningLevel: 200,alarmLevel: 240 },
  { stationName: "Łąki",warningLevel: 280,alarmLevel: 310 },
  { stationName: "Łeba",warningLevel: 570,alarmLevel: 610 },
  { stationName: "Łowicz",warningLevel: 350,alarmLevel: 400 },
  { stationName: "Łozy",warningLevel: 280,alarmLevel: 330 },
  { stationName: "Łozy",warningLevel: 350,alarmLevel: 400 },
  { stationName: "Malczyce",warningLevel: 600,alarmLevel: 700 },
  { stationName: "Malowa Góra",warningLevel: 310,alarmLevel: 350 },
  { stationName: "Małkinia",warningLevel: 350,alarmLevel: 430 },
  { stationName: "Michałów",warningLevel: 110,alarmLevel: 170 },
  { stationName: "Mietków",warningLevel: 280,alarmLevel: 300 },
  { stationName: "Międzychód",warningLevel: 380,alarmLevel: 430 },
  { stationName: "Mirków",warningLevel: 230,alarmLevel: 270 },
  { stationName: "Mirsk",warningLevel: 420,alarmLevel: 470 },
  { stationName: "Mniszek",warningLevel: 270,alarmLevel: 310 },
  { stationName: "Mocha",warningLevel: 370,alarmLevel: 420 },
  { stationName: "Mosina",warningLevel: 160,alarmLevel: 250 },
  { stationName: "Mościsko",warningLevel: 220,alarmLevel: 250 },
  { stationName: "Mstów",warningLevel: 120,alarmLevel: 170 },
  { stationName: "Mszana Dolna",warningLevel: 320,alarmLevel: 380 },
  { stationName: "Muszyna-Milik",warningLevel: 260,alarmLevel: 350 },
  { stationName: "Nakło-Zachód",warningLevel: 320,alarmLevel: 360 },
  { stationName: "Narewka",warningLevel: 260,alarmLevel: 290 },
  { stationName: "Niechmirów",warningLevel: 170,alarmLevel: 220 },
  { stationName: "Niedzica",warningLevel: 200,alarmLevel: 260 },
  { stationName: "Niemodlin",warningLevel: 320,alarmLevel: 350 },
  { stationName: "Nietków",warningLevel: 370,alarmLevel: 400 },
  { stationName: "Nietulisko Duże",warningLevel: 460,alarmLevel: 510 },
  { stationName: "Niwki",warningLevel: 200,alarmLevel: 250 },
  { stationName: "Nowa Pasłęka",warningLevel: 590,alarmLevel: 630 },
  { stationName: "Nowa Sól",warningLevel: 400,alarmLevel: 450 },
  { stationName: "Nowakowo",warningLevel: 590,alarmLevel: 630 },
  { stationName: "Nowe Drezdenko",warningLevel: 290,alarmLevel: 340 },
  { stationName: "Nowe Miasto Lubawskie",warningLevel: 330,alarmLevel: 340 },
  { stationName: "Nowe Sadłuki",warningLevel: 300,alarmLevel: 390 },
  { stationName: "Nowogród Bobrzański",warningLevel: 250,alarmLevel: 300 },
  { stationName: "Nowosielce",warningLevel: 210,alarmLevel: 260 },
  { stationName: "Nowosiółki",warningLevel: 200,alarmLevel: 240 },
  { stationName: "Nowotki",warningLevel: 570,alarmLevel: 590 },
  { stationName: "Nowy Dwór Gdański",warningLevel: 570,alarmLevel: 590 },
  { stationName: "Nowy Targ-Kowaniec",warningLevel: 300,alarmLevel: 380 },
  { stationName: "Odolanów",warningLevel: 120,alarmLevel: 150 },
  { stationName: "Olchowce",warningLevel: 280,alarmLevel: 380 },
  { stationName: "Olza",warningLevel: 500,alarmLevel: 610 },
  { stationName: "Oława",warningLevel: 500,alarmLevel: 560 },
  { stationName: "Oława",warningLevel: 200,alarmLevel: 250 },
  { stationName: "Ołobok",warningLevel: 220,alarmLevel: 260 },
  { stationName: "Opole-Groszowice",warningLevel: 500,alarmLevel: 600 },
  { stationName: "Orzechowo",warningLevel: 320,alarmLevel: 400 },
  { stationName: "Osetno",warningLevel: 260,alarmLevel: 330 },
  { stationName: "Osjaków",warningLevel: 280,alarmLevel: 340 },
  { stationName: "Osłonka",warningLevel: 570,alarmLevel: 590 },
  { stationName: "Ostróda",warningLevel: 500,alarmLevel: 510 },
  { stationName: "Ostróżno",warningLevel: 250,alarmLevel: 300 },
  { stationName: "Ozimek",warningLevel: 210,alarmLevel: 250 },
  { stationName: "Pasłęk",warningLevel: 620,alarmLevel: 630 },
  { stationName: "Piaseczno 2",warningLevel: 300,alarmLevel: 350 },
  { stationName: "Piątnica",warningLevel: 300,alarmLevel: 370 },
  { stationName: "Piechowice",warningLevel: 150,alarmLevel: 200 },
  { stationName: "Pierzchały",warningLevel: 570,alarmLevel: 630 },
  { stationName: "Pierzchały_2",warningLevel: 560,alarmLevel: 600 },
  { stationName: "Piła",warningLevel: 190,alarmLevel: 220 },
  { stationName: "Piwonice",warningLevel: 200,alarmLevel: 230 },
  { stationName: "Podgórzyn",warningLevel: 290,alarmLevel: 320 },
  { stationName: "Podkępie",warningLevel: 330,alarmLevel: 410 },
  { stationName: "Polana",warningLevel: 380,alarmLevel: 430 },
  { stationName: "Połęcko",warningLevel: 310,alarmLevel: 350 },
  { stationName: "Popowo",warningLevel: 330,alarmLevel: 370 },
  { stationName: "Porajów",warningLevel: 120,alarmLevel: 160 },
  { stationName: "Poronin",warningLevel: 220,alarmLevel: 250 },
  { stationName: "Prudnik",warningLevel: 180,alarmLevel: 230 },
  { stationName: "Przeczyce",warningLevel: 100,alarmLevel: 150 },
  { stationName: "Przemyśl",warningLevel: 380,alarmLevel: 570 },
  { stationName: "Przewoźniki",warningLevel: 300,alarmLevel: 340 },
  { stationName: "Przewóz",warningLevel: 290,alarmLevel: 350 },
  { stationName: "Pszczyna",warningLevel: 290,alarmLevel: 340 },
  { stationName: "Ptusza",warningLevel: 240,alarmLevel: 290 },
  { stationName: "Puck",warningLevel: 550,alarmLevel: 570 },
  { stationName: "Puławy",warningLevel: 250,alarmLevel: 300 },
  { stationName: "Pustynia",warningLevel: 330,alarmLevel: 480 },
  { stationName: "Pyzdry",warningLevel: 410,alarmLevel: 450 },
  { stationName: "Rabka 2",warningLevel: 140,alarmLevel: 180 },
  { stationName: "Racibórz-Miedonia",warningLevel: 400,alarmLevel: 600 },
  { stationName: "Racławice Śląskie",warningLevel: 300,alarmLevel: 350 },
  { stationName: "Radocha",warningLevel: 90,alarmLevel: 130 },
  { stationName: "Radziszów",warningLevel: 310,alarmLevel: 400 },
  { stationName: "Resko",warningLevel: 410,alarmLevel: 430 },
  { stationName: "Ręczyn",warningLevel: 350,alarmLevel: 380 },
  { stationName: "Rodzone",warningLevel: 280,alarmLevel: 320 },
  { stationName: "Ruda Kozielska",warningLevel: 250,alarmLevel: 310 },
  { stationName: "Rybotycze",warningLevel: 270,alarmLevel: 350 },
  { stationName: "Rzeszotary",warningLevel: 200,alarmLevel: 230 },
  { stationName: "Santok",warningLevel: 250,alarmLevel: 330 },
  { stationName: "Santok",warningLevel: 420,alarmLevel: 490 },
  { stationName: "Sarzyna",warningLevel: 260,alarmLevel: 320 },
  { stationName: "Sępopol",warningLevel: 420,alarmLevel: 450 },
  { stationName: "Sieniawa",warningLevel: 220,alarmLevel: 280 },
  { stationName: "Sieniawka",warningLevel: 160,alarmLevel: 200 },
  { stationName: "Skoczów",warningLevel: 210,alarmLevel: 260 },
  { stationName: "Słowik",warningLevel: 260,alarmLevel: 300 },
  { stationName: "Słubice",warningLevel: 360,alarmLevel: 410 },
  { stationName: "Słupsk",warningLevel: 220,alarmLevel: 260 },
  { stationName: "Smolajny",warningLevel: 280,alarmLevel: 300 },
  { stationName: "Smolice",warningLevel: 450,alarmLevel: 630 },
  { stationName: "Smołdzino",warningLevel: 170,alarmLevel: 200 },
  { stationName: "Smukała",warningLevel: 230,alarmLevel: 260 },
  { stationName: "Sobianowice",warningLevel: 240,alarmLevel: 270 },
  { stationName: "Sochonie",warningLevel: 100,alarmLevel: 120 },
  { stationName: "Sokołda",warningLevel: 250,alarmLevel: 300 },
  { stationName: "Sosnówka",warningLevel: 60,alarmLevel: 80 },
  { stationName: "Soszyca",warningLevel: 120,alarmLevel: 140 },
  { stationName: "Stargard",warningLevel: 250,alarmLevel: 280 },
  { stationName: "Stary Kraków",warningLevel: 460,alarmLevel: 500 },
  { stationName: "Staszów",warningLevel: 220,alarmLevel: 260 },
  { stationName: "Stradomka",warningLevel: 280,alarmLevel: 350 },
  { stationName: "Suchy Dąb",warningLevel: 600,alarmLevel: 620 },
  { stationName: "Suraż",warningLevel: 320,alarmLevel: 340 },
  { stationName: "Szaflary",warningLevel: 310,alarmLevel: 380 },
  { stationName: "Szczawne",warningLevel: 140,alarmLevel: 190 },
  { stationName: "Szczecin Most Długi",warningLevel: 570,alarmLevel: 600 },
  { stationName: "Szczecin-Podjuchy",warningLevel: 580,alarmLevel: 610 },
  { stationName: "Szkwa",warningLevel: 460,alarmLevel: 500 },
  { stationName: "Szprotawa",warningLevel: 230,alarmLevel: 270 },
  { stationName: "Szreńsk",warningLevel: 130,alarmLevel: 180 },
  { stationName: "Ścinawa",warningLevel: 350,alarmLevel: 400 },
  { stationName: "Ślęza",warningLevel: 270,alarmLevel: 300 },
  { stationName: "Świebodzice",warningLevel: 140,alarmLevel: 160 },
  { stationName: "Świerkocin",warningLevel: 450,alarmLevel: 500 },
  { stationName: "Świerzawa",warningLevel: 150,alarmLevel: 220 },
  { stationName: "Świnoujście",warningLevel: 560,alarmLevel: 580 },
  { stationName: "Tczew",warningLevel: 700,alarmLevel: 820 },
  { stationName: "Terka",warningLevel: 200,alarmLevel: 260 },
  { stationName: "Tolkmicko",warningLevel: 590,alarmLevel: 630 },
  { stationName: "Trąbczyn",warningLevel: 180,alarmLevel: 230 },
  { stationName: "Trestno",warningLevel: 380,alarmLevel: 450 },
  { stationName: "Trzciniec",warningLevel: 280,alarmLevel: 330 },
  { stationName: "Trzebież",warningLevel: 540,alarmLevel: 560 },
  { stationName: "Tuchola",warningLevel: 140,alarmLevel: 190 },
  { stationName: "Tujsk",warningLevel: 570,alarmLevel: 590 },
  { stationName: "Turoszów",warningLevel: 360,alarmLevel: 420 },
  { stationName: "Tychówko",warningLevel: 320,alarmLevel: 380 },
  { stationName: "Ujście",warningLevel: 310,alarmLevel: 330 },
  { stationName: "Ujście Nysy Kłodzkiej",warningLevel: 400,alarmLevel: 530 },
  { stationName: "Ustka",warningLevel: 570,alarmLevel: 600 },
  { stationName: "Ustroń-Obłaziec",warningLevel: 180,alarmLevel: 230 },
  { stationName: "Wadowice",warningLevel: 370,alarmLevel: 490 },
  { stationName: "Walery",warningLevel: 300,alarmLevel: 340 },
  { stationName: "Wampierzów",warningLevel: 340,alarmLevel: 450 },
  { stationName: "Wąsosz",warningLevel: 250,alarmLevel: 300 },
  { stationName: "Wejherowo",warningLevel: 130,alarmLevel: 160 },
  { stationName: "Widuchowa",warningLevel: 630,alarmLevel: 650 },
  { stationName: "Winnica",warningLevel: 80,alarmLevel: 100 },
  { stationName: "Wisła",warningLevel: 150,alarmLevel: 180 },
  { stationName: "Wisła-Czarne",warningLevel: 100,alarmLevel: 120 },
  { stationName: "Wisła-Czarne (Biała Wisełka)",warningLevel: 90,alarmLevel: 110 },
  { stationName: "Wiślina",warningLevel: 560,alarmLevel: 580 },
  { stationName: "Władysławowo",warningLevel: 550,alarmLevel: 570 },
  { stationName: "Włochy",warningLevel: 300,alarmLevel: 450 },
  { stationName: "Włocławek",warningLevel: 600,alarmLevel: 650 },
  { stationName: "Wojanów",warningLevel: 260,alarmLevel: 320 },
  { stationName: "Wolin",warningLevel: 560,alarmLevel: 580 },
  { stationName: "Zabuże",warningLevel: 450,alarmLevel: 520 },
  { stationName: "Zagrodno",warningLevel: 120,alarmLevel: 150 },
  { stationName: "Zakopane-Harenda",warningLevel: 200,alarmLevel: 240 },
  { stationName: "Zaruzie",warningLevel: 220,alarmLevel: 260 },
  { stationName: "Zator",warningLevel: 240,alarmLevel: 370 },
  { stationName: "Zatwarnica",warningLevel: 250,alarmLevel: 320 },
  { stationName: "Zborowice",warningLevel: 230,alarmLevel: 250 },
  { stationName: "Zbytowa",warningLevel: 310,alarmLevel: 350 },
  { stationName: "Zgorzelec",warningLevel: 190,alarmLevel: 220 },
  { stationName: "Zgorzelec",warningLevel: 340,alarmLevel: 400 },
  { stationName: "Żagań",warningLevel: 130,alarmLevel: 150 },
  { stationName: "Żuków",warningLevel: 300,alarmLevel: 350 },
  { stationName: "Annopol",warningLevel: 500,alarmLevel: 550 },
  { stationName: "Banie Mazurskie",warningLevel: 260,alarmLevel: 290 },
  { stationName: "Białobrzegi",warningLevel: 200,alarmLevel: 240 },
  { stationName: "Białośliwie",warningLevel: 280,alarmLevel: 330 },
  { stationName: "Błażkowa",warningLevel: 150,alarmLevel: 180 },
  { stationName: "Bogdaszowice",warningLevel: 180,alarmLevel: 220 },
  { stationName: "Borkowo",warningLevel: 280,alarmLevel: 300 },
  { stationName: "Borzęcin",warningLevel: 300,alarmLevel: 400 },
  { stationName: "Brańsk",warningLevel: 250,alarmLevel: 300 },
  { stationName: "Brzegi",warningLevel: 240,alarmLevel: 300 },
  { stationName: "Brzeźnica",warningLevel: 270,alarmLevel: 450 },
  { stationName: "Burzenin",warningLevel: 280,alarmLevel: 320 },
  { stationName: "Burzyn",warningLevel: 380,alarmLevel: 400 },
  { stationName: "Bzin",warningLevel: 180,alarmLevel: 230 },
  { stationName: "Charytany",warningLevel: 330,alarmLevel: 470 },
  { stationName: "Chełmno",warningLevel: 510,alarmLevel: 630 },
  { stationName: "Ciecholewy",warningLevel: 210,alarmLevel: 240 },
  { stationName: "Ciężkowice",warningLevel: 350,alarmLevel: 500 },
  { stationName: "Cisna",warningLevel: 190,alarmLevel: 240 },
  { stationName: "Czachy",warningLevel: 320,alarmLevel: 360 },
  { stationName: "Czarna Woda",warningLevel: 130,alarmLevel: 150 },
  { stationName: "Czchów",warningLevel: 310,alarmLevel: 410 },
  { stationName: "Czechowice-Dziedzice",warningLevel: 330,alarmLevel: 420 },
  { stationName: "Czekarzewice",warningLevel: 160,alarmLevel: 220 },
  { stationName: "Czernichów-Prom",warningLevel: 580,alarmLevel: 840 },
  { stationName: "Dąbie",warningLevel: 250,alarmLevel: 300 },
  { stationName: "Dąbrowa Bolesławiecka",warningLevel: 300,alarmLevel: 350 },
  { stationName: "Dęblin",warningLevel: 400,alarmLevel: 500 },
  { stationName: "Dębowo",warningLevel: 270,alarmLevel: 300 },
  { stationName: "Dobczyce",warningLevel: 600,alarmLevel: 690 },
  { stationName: "Dobrylas",warningLevel: 250,alarmLevel: 290 },
  { stationName: "Dorohusk",warningLevel: 290,alarmLevel: 430 },
  { stationName: "Dunino",warningLevel: 130,alarmLevel: 200 },
  { stationName: "Działoszyn",warningLevel: 530,alarmLevel: 570 },
  { stationName: "Ełk",warningLevel: 200,alarmLevel: 230 },
  { stationName: "Fasty",warningLevel: 220,alarmLevel: 250 },
  { stationName: "Fordon",warningLevel: 530,alarmLevel: 650 },
  { stationName: "Frankopol",warningLevel: 250,alarmLevel: 350 },
  { stationName: "Giżycko",warningLevel: 130,alarmLevel: 150 },
  { stationName: "Gliwice",warningLevel: 160,alarmLevel: 220 },
  { stationName: "Godowa",warningLevel: 740,alarmLevel: 880 },
  { stationName: "Gołkowice",warningLevel: 320,alarmLevel: 400 },
  { stationName: "Goręczyno",warningLevel: 210,alarmLevel: 240 },
  { stationName: "Gorlice",warningLevel: 390,alarmLevel: 450 },
  { stationName: "Gorliczyna",warningLevel: 360,alarmLevel: 480 },
  { stationName: "Gorzów Wielkopolski",warningLevel: 390,alarmLevel: 470 },
  { stationName: "Grabowo",warningLevel: 160,alarmLevel: 170 },
  { stationName: "Gusin",warningLevel: 370,alarmLevel: 420 },
  { stationName: "Harasiuki",warningLevel: 270,alarmLevel: 330 },
  { stationName: "Iskrzynia",warningLevel: 350,alarmLevel: 480 },
  { stationName: "Jakubkowice",warningLevel: 200,alarmLevel: 350 },
  { stationName: "Jeleń",warningLevel: 280,alarmLevel: 330 },
  { stationName: "Jordanów",warningLevel: 270,alarmLevel: 350 },
  { stationName: "Kalisty",warningLevel: 170,alarmLevel: 190 },
  { stationName: "Kamieniec Ząbkowicki",warningLevel: 300,alarmLevel: 340 },
  { stationName: "Kamionka",warningLevel: 180,alarmLevel: 240 },
  { stationName: "Karsy",warningLevel: 550,alarmLevel: 750 },
  { stationName: "Kasinka Mała",warningLevel: 350,alarmLevel: 420 },
  { stationName: "Kazanów",warningLevel: 195,alarmLevel: 270 },
  { stationName: "Kępa Polska",warningLevel: 450,alarmLevel: 500 },
  { stationName: "Klęczany",warningLevel: 260,alarmLevel: 380 },
  { stationName: "Koło",warningLevel: 340,alarmLevel: 390 },
  { stationName: "Koło",warningLevel: 460,alarmLevel: 680 },
  { stationName: "Kościelec",warningLevel: 240,alarmLevel: 270 },
  { stationName: "Kościelisko-Kiry",warningLevel: 140,alarmLevel: 180 },
  { stationName: "Kośmin",warningLevel: 350,alarmLevel: 400 },
  { stationName: "Krajowice",warningLevel: 330,alarmLevel: 450 },
  { stationName: "Krasków",warningLevel: 200,alarmLevel: 250 },
  { stationName: "Krasnystaw",warningLevel: 420,alarmLevel: 470 },
  { stationName: "Krempna-Kotań",warningLevel: 360,alarmLevel: 410 },
  { stationName: "Kręciwilk",warningLevel: 80,alarmLevel: 130 },
  { stationName: "Krosno",warningLevel: 350,alarmLevel: 480 },
  { stationName: "Krościenko",warningLevel: 320,alarmLevel: 390 },
  { stationName: "Krościenko",warningLevel: 160,alarmLevel: 210 },
  { stationName: "Krupski Młyn",warningLevel: 160,alarmLevel: 250 },
  { stationName: "Kryłów",warningLevel: 440,alarmLevel: 540 },
  { stationName: "Krzyczew",warningLevel: 380,alarmLevel: 480 },
  { stationName: "Kudowa-Zdrój-Zakrze",warningLevel: 280,alarmLevel: 310 },
  { stationName: "Kule",warningLevel: 250,alarmLevel: 300 },
  { stationName: "Kulesze-Chobotki",warningLevel: 330,alarmLevel: 360 },
  { stationName: "Kunkowa",warningLevel: 200,alarmLevel: 230 },
  { stationName: "Kuźnica Sulikowska",warningLevel: 210,alarmLevel: 260 },
  { stationName: "Las",warningLevel: 400,alarmLevel: 550 },
  { stationName: "Ląd",warningLevel: 330,alarmLevel: 370 },
  { stationName: "Lądek-Zdrój",warningLevel: 80,alarmLevel: 120 },
  { stationName: "Lubień",warningLevel: 120,alarmLevel: 140 },
  { stationName: "Ludźmierz",warningLevel: 230,alarmLevel: 300 },
  { stationName: "Ludźmierz",warningLevel: 280,alarmLevel: 350 },
  { stationName: "Łabowa",warningLevel: 180,alarmLevel: 250 },
  { stationName: "Łabuzie",warningLevel: 620,alarmLevel: 810 },
  { stationName: "Łochów",warningLevel: 300,alarmLevel: 350 },
  { stationName: "Łodygowice",warningLevel: 540,alarmLevel: 580 },
  { stationName: "Łomnica",warningLevel: 320,alarmLevel: 380 },
  { stationName: "Łupawa",warningLevel: 130,alarmLevel: 160 },
  { stationName: "Łysa Polana",warningLevel: 220,alarmLevel: 260 },
  { stationName: "Maków Mazowiecki",warningLevel: 370,alarmLevel: 390 },
  { stationName: "Maldanin",warningLevel: 140,alarmLevel: 160 },
  { stationName: "Michalów",warningLevel: 140,alarmLevel: 190 },
  { stationName: "Michałów",warningLevel: 160,alarmLevel: 190 },
  { stationName: "Mieduniszki",warningLevel: 400,alarmLevel: 450 },
  { stationName: "Mielec 2",warningLevel: 480,alarmLevel: 650 },
  { stationName: "Międzylesie",warningLevel: 180,alarmLevel: 200 },
  { stationName: "Mikołajki",warningLevel: 110,alarmLevel: 120 },
  { stationName: "Mikuszowice",warningLevel: 170,alarmLevel: 200 },
  { stationName: "Miłoszewo",warningLevel: 250,alarmLevel: 260 },
  { stationName: "Modlin",warningLevel: 650,alarmLevel: 700 },
  { stationName: "Morawica",warningLevel: 250,alarmLevel: 340 },
  { stationName: "Mszana Dolna",warningLevel: 240,alarmLevel: 340 },
  { stationName: "Muszyna",warningLevel: 210,alarmLevel: 290 },
  { stationName: "Namysłów",warningLevel: 210,alarmLevel: 250 },
  { stationName: "Narew",warningLevel: 170,alarmLevel: 200 },
  { stationName: "Nielisz",warningLevel: 200,alarmLevel: 230 },
  { stationName: "Nienowice",warningLevel: 340,alarmLevel: 460 },
  { stationName: "Nisko",warningLevel: 370,alarmLevel: 500 },
  { stationName: "Nowa Wieś Podgórna",warningLevel: 430,alarmLevel: 480 },
  { stationName: "Nowe Miasto",warningLevel: 160,alarmLevel: 200 },
  { stationName: "Nowogrodziec",warningLevel: 330,alarmLevel: 380 },
  { stationName: "Nowogród",warningLevel: 360,alarmLevel: 400 },
  { stationName: "Nowy Sącz",warningLevel: 300,alarmLevel: 380 },
  { stationName: "Nowy Sącz",warningLevel: 250,alarmLevel: 380 },
  { stationName: "Nowy Sącz",warningLevel: 200,alarmLevel: 260 },
  { stationName: "Nowy Targ",warningLevel: 260,alarmLevel: 350 },
  { stationName: "Nysa",warningLevel: 380,alarmLevel: 450 },
  { stationName: "Oborniki",warningLevel: 420,alarmLevel: 560 },
  { stationName: "Odolanów",warningLevel: 160,alarmLevel: 190 },
  { stationName: "Odrzywół",warningLevel: 220,alarmLevel: 260 },
  { stationName: "Ojców",warningLevel: 170,alarmLevel: 210 },
  { stationName: "Olsztyn-Kortowo",warningLevel: 140,alarmLevel: 160 },
  { stationName: "Osowiec",warningLevel: 400,alarmLevel: 430 },
  { stationName: "Osowiec",warningLevel: 460,alarmLevel: 490 },
  { stationName: "Ostrołęka",warningLevel: 360,alarmLevel: 380 },
  { stationName: "Osuchy",warningLevel: 320,alarmLevel: 400 },
  { stationName: "Oświęcim",warningLevel: 370,alarmLevel: 460 },
  { stationName: "Pakość",warningLevel: 260,alarmLevel: 280 },
  { stationName: "Pastwiska",warningLevel: 200,alarmLevel: 250 },
  { stationName: "Pewel Mała",warningLevel: 150,alarmLevel: 230 },
  { stationName: "Piątnica-Łomża",warningLevel: 410,alarmLevel: 460 },
  { stationName: "Pisz",warningLevel: 270,alarmLevel: 290 },
  { stationName: "Piwoń",warningLevel: 270,alarmLevel: 330 },
  { stationName: "Pleśno",warningLevel: 160,alarmLevel: 200 },
  { stationName: "Ploski",warningLevel: 330,alarmLevel: 370 },
  { stationName: "Poddębice",warningLevel: 240,alarmLevel: 290 },
  { stationName: "Podgórze",warningLevel: 290,alarmLevel: 330 },
  { stationName: "Połaniec",warningLevel: 290,alarmLevel: 350 },
  { stationName: "Popędzynka",warningLevel: 580,alarmLevel: 750 },
  { stationName: "Poraj",warningLevel: 220,alarmLevel: 290 },
  { stationName: "Posoka",warningLevel: 260,alarmLevel: 300 },
  { stationName: "Poznań-Most Rocha",warningLevel: 400,alarmLevel: 500 },
  { stationName: "Prosna",warningLevel: 300,alarmLevel: 330 },
  { stationName: "Prostki",warningLevel: 190,alarmLevel: 220 },
  { stationName: "Prynowo",warningLevel: 250,alarmLevel: 280 },
  { stationName: "Przechody",warningLevel: 330,alarmLevel: 360 },
  { stationName: "Przedbórz",warningLevel: 360,alarmLevel: 400 },
  { stationName: "Przystań",warningLevel: 160,alarmLevel: 180 },
  { stationName: "Ptaki",warningLevel: 210,alarmLevel: 240 },
  { stationName: "Puławy-Azoty",warningLevel: 450,alarmLevel: 550 },
  { stationName: "Pustków",warningLevel: 520,alarmLevel: 720 },
  { stationName: "Radomyśl",warningLevel: 460,alarmLevel: 620 },
  { stationName: "Rajcza",warningLevel: 290,alarmLevel: 370 },
  { stationName: "Rajgród",warningLevel: 225,alarmLevel: 240 },
  { stationName: "Rajgród",warningLevel: 140,alarmLevel: 160 },
  { stationName: "Raków",warningLevel: 220,alarmLevel: 260 },
  { stationName: "Rogożek",warningLevel: 330,alarmLevel: 380 },
  { stationName: "Rogóźno",warningLevel: 240,alarmLevel: 290 },
  { stationName: "Ropa",warningLevel: 280,alarmLevel: 370 },
  { stationName: "Ruda Jastkowska",warningLevel: 160,alarmLevel: 240 },
  { stationName: "Rzepin",warningLevel: 400,alarmLevel: 420 },
  { stationName: "Rzeszów",warningLevel: 300,alarmLevel: 420 },
  { stationName: "Rzuchów",warningLevel: 570,alarmLevel: 750 },
  { stationName: "Rzymówka",warningLevel: 240,alarmLevel: 300 },
  { stationName: "Sandomierz",warningLevel: 420,alarmLevel: 610 },
  { stationName: "Sieradz",warningLevel: 390,alarmLevel: 440 },
  { stationName: "Sierosławice",warningLevel: 530,alarmLevel: 700 },
  { stationName: "Skawica Dolna",warningLevel: 190,alarmLevel: 240 },
  { stationName: "Skorogoszcz",warningLevel: 250,alarmLevel: 280 },
  { stationName: "Sławsk",warningLevel: 450,alarmLevel: 480 },
  { stationName: "Spała",warningLevel: 220,alarmLevel: 280 },
  { stationName: "Sromowce Wyżne",warningLevel: 280,alarmLevel: 360 },
  { stationName: "Staniszcze Wielkie",warningLevel: 230,alarmLevel: 300 },
  { stationName: "Stary Raduszec",warningLevel: 450,alarmLevel: 500 },
  { stationName: "Stary Sącz",warningLevel: 300,alarmLevel: 400 },
  { stationName: "Strękowa Góra",warningLevel: 420,alarmLevel: 440 },
  { stationName: "Stróża",warningLevel: 220,alarmLevel: 290 },
  { stationName: "Strzyżów",warningLevel: 650,alarmLevel: 800 },
  { stationName: "Stuposiany",warningLevel: 210,alarmLevel: 250 },
  { stationName: "Sucha Beskidzka",warningLevel: 215,alarmLevel: 285 },
  { stationName: "Sulejów-Kopalnia",warningLevel: 230,alarmLevel: 260 },
  { stationName: "Supraśl",warningLevel: 220,alarmLevel: 260 },
  { stationName: "Szabelnia",warningLevel: 70,alarmLevel: 100 },
  { stationName: "Szalejów Dolny",warningLevel: 160,alarmLevel: 180 },
  { stationName: "Szczerców",warningLevel: 190,alarmLevel: 230 },
  { stationName: "Szczucin",warningLevel: 460,alarmLevel: 660 },
  { stationName: "Szprotawa",warningLevel: 200,alarmLevel: 250 },
  { stationName: "Sztabin",warningLevel: 270,alarmLevel: 290 },
  { stationName: "Śrem",warningLevel: 400,alarmLevel: 460 },
  { stationName: "Tchórzew",warningLevel: 350,alarmLevel: 400 },
  { stationName: "Tłumaczów",warningLevel: 180,alarmLevel: 220 },
  { stationName: "Tokarnia",warningLevel: 240,alarmLevel: 300 },
  { stationName: "Tomaryny",warningLevel: 280,alarmLevel: 300 },
  { stationName: "Topoliny",warningLevel: 220,alarmLevel: 380 },
  { stationName: "Toruń",warningLevel: 530,alarmLevel: 650 },
  { stationName: "Trawniki",warningLevel: 450,alarmLevel: 500 },
  { stationName: "Trybsz 2",warningLevel: 280,alarmLevel: 320 },
  { stationName: "Tryńcza",warningLevel: 540,alarmLevel: 720 },
  { stationName: "Trzebiatów",warningLevel: 350,alarmLevel: 370 },
  { stationName: "Turawa",warningLevel: 210,alarmLevel: 250 },
  { stationName: "Tylmanowa",warningLevel: 200,alarmLevel: 250 },
  { stationName: "Ujsoły",warningLevel: 270,alarmLevel: 320 },
  { stationName: "Uniejów",warningLevel: 220,alarmLevel: 270 },
  { stationName: "Uście Gorlickie",warningLevel: 230,alarmLevel: 280 },
  { stationName: "Uście Gorlickie-Zdynia",warningLevel: 550,alarmLevel: 600 },
  { stationName: "Warszawa-Bulwary",warningLevel: 600,alarmLevel: 650 },
  { stationName: "Warszawa-Nadwilanówka",warningLevel: 750,alarmLevel: 800 },
  { stationName: "Wąchock",warningLevel: 140,alarmLevel: 190 },
  { stationName: "Węgorzewo",warningLevel: 250,alarmLevel: 280 },
  { stationName: "Wilkanów",warningLevel: 140,alarmLevel: 160 },
  { stationName: "Wirkowice",warningLevel: 290,alarmLevel: 350 },
  { stationName: "Wizna",warningLevel: 440,alarmLevel: 470 },
  { stationName: "Włodawa",warningLevel: 300,alarmLevel: 390 },
  { stationName: "Wólka Mlądzka",warningLevel: 210,alarmLevel: 300 },
  { stationName: "Wronki",warningLevel: 380,alarmLevel: 470 },
  { stationName: "Wychódźc",warningLevel: 580,alarmLevel: 630 },
  { stationName: "Wyrzysk",warningLevel: 160,alarmLevel: 200 },
  { stationName: "Wyszków",warningLevel: 400,alarmLevel: 450 },
  { stationName: "Wyszogród",warningLevel: 500,alarmLevel: 550 },
  { stationName: "Zagórz",warningLevel: 180,alarmLevel: 240 },
  { stationName: "Zakłodzie",warningLevel: 190,alarmLevel: 230 },
  { stationName: "Zaliwie-Piegawki",warningLevel: 220,alarmLevel: 270 },
  { stationName: "Zambski Kościelne",warningLevel: 420,alarmLevel: 480 },
  { stationName: "Zapałów",warningLevel: 250,alarmLevel: 350 },
  { stationName: "Zawady",warningLevel: 380,alarmLevel: 400 },
  { stationName: "Zawichost",warningLevel: 480,alarmLevel: 620 },
  { stationName: "Zboiska",warningLevel: 250,alarmLevel: 320 },
  { stationName: "Zgłobice",warningLevel: 450,alarmLevel: 600 },
  { stationName: "Żabnica",warningLevel: 160,alarmLevel: 200 },
  { stationName: "Żabno",warningLevel: 530,alarmLevel: 750 },
  { stationName: "Żagań",warningLevel: 340,alarmLevel: 400 },
  { stationName: "Żarnowa",warningLevel: 400,alarmLevel: 490 },
  { stationName: "Żelazno",warningLevel: 110,alarmLevel: 140 },
  { stationName: "Żółków",warningLevel: 220,alarmLevel: 350 },
  { stationName: "Żywiec",warningLevel: 280,alarmLevel: 340 },
  { stationName: "Łękawica",warningLevel: 300,alarmLevel: 350 },
  { stationName: "Niwka",warningLevel: 260,alarmLevel: 280 },
  { stationName: "Płock",warningLevel: 210,alarmLevel: 250 },
  { stationName: "Różan",warningLevel: 400,alarmLevel: 450 },
  { stationName: "Bojszowy",warningLevel: 170,alarmLevel: 230 },
  { stationName: "Osielec",warningLevel: 230,alarmLevel: 280 },
  { stationName: "Pińczów",warningLevel: 250,alarmLevel: 300 },
  { stationName: "Proszówki",warningLevel: 500,alarmLevel: 700 },
  { stationName: "Rudze",warningLevel: 220,alarmLevel: 320 },
  { stationName: "Skwierzyna",warningLevel: 380,alarmLevel: 460 },
  { stationName: "Sucha Beskidzka",warningLevel: 220,alarmLevel: 270 },
  { stationName: "Wisła-Czarne (Czarna Wisełka)",warningLevel: 120,alarmLevel: 170 },

];

/**
 * Funkcja znajdująca dane poziomów dla określonej stacji
 * @param {string} stationName - Nazwa stacji
 * @returns {Object|null} - Dane poziomów lub null jeśli nie znaleziono
 */
export const findStationLevels = (stationName) => {
  if (!stationName) return null;
  
  // Próbuj znaleźć dokładne dopasowanie
  const exactMatch = HYDRO_LEVELS.find(
    station => station.stationName.toLowerCase() === stationName.toLowerCase()
  );
  
  if (exactMatch) {
    return exactMatch;
  }
  
  // Jeśli nie znaleziono dokładnego dopasowania, szukaj częściowego
  const partialMatch = HYDRO_LEVELS.find(
    station => station.stationName.toLowerCase().includes(stationName.toLowerCase()) || 
              stationName.toLowerCase().includes(station.stationName.toLowerCase())
  );
  
  return partialMatch || null;
};

/**
 * Określa status stacji na podstawie aktualnego poziomu
 * @param {number} currentLevel - Aktualny poziom wody
 * @param {number} warningLevel - Poziom ostrzegawczy
 * @param {number} alarmLevel - Poziom alarmowy
 * @returns {string} - Status: 'normal', 'warning', 'alarm'
 */
export const determineStationStatus = (currentLevel, warningLevel, alarmLevel) => {
  if (currentLevel >= alarmLevel) return 'alarm';
  if (currentLevel >= warningLevel) return 'warning';
  return 'normal';
};